In [2]:
from footium_api import GqlConnection
from footium_api.queries import get_formations_as_pd

gql = GqlConnection()

Basic demo of how to get the formations

In [5]:
formations = get_formations_as_pd(gql)

In [4]:
formations.head(len(formations))

            CF LW RW AM LM CM RM DM LWB RWB LB CB RB GK
Formation
3-4-3        1  1  1  0  1  2  1  0   0   0  0  3  0  1
3-4-3-A      1  1  1  1  1  0  1  1   0   0  0  3  0  1
3-5-2        2  0  0  0  1  3  1  0   0   0  0  3  0  1
3-1-4-2      2  0  0  0  1  2  1  1   0   0  0  3  0  1
3-4-1-2      2  0  0  1  1  2  1  0   0   0  0  3  0  1
5-3-2        2  0  0  0  0  3  0  0   1   1  0  3  0  1
5-4-1        1  0  0  0  1  2  1  0   1   1  0  3  0  1
5-4-1-D      1  0  0  1  1  0  1  1   1   1  0  3  0  1
5-2-1-2      2  0  0  1  0  2  0  0   1   1  0  3  0  1
5-2-3        1  1  1  0  0  2  0  0   1   1  0  3  0  1
4-4-2        2  0  0  0  1  2  1  0   0   0  1  2  1  1
4-4-2-H      2  0  0  0  1  0  1  2   0   0  1  2  1  1
4-1-2-1-2-N  2  0  0  1  0  2  0  1   0   0  1  2  1  1
4-1-2-1-2    2  0  0  1  1  0  1  1   0   0  1  2  1  1
4-5-1        1  0  0  2  1  1  1  0   0   0  1  2  1  1
4-2-3-1      1  0  0  1  1  0  1  2   0   0  1  2  1  1
4-3-3        1  1  1  0  0  3  0  0   0   0  1  2  1  1
4-3-3-A      1  1  1  1  0  2  0  0   0   0  1  2  1  1
4-3-3-D      1  1  1  0  0  1  0  2   0   0  1  2  1  1
4-3-3-H      1  1  1  0  0  2  0  1   0   0  1  2  1  1
4-1-4-1      1  0  0  0  1  2  1  1   0   0  1  2  1  1
4-2-2-2      2  0  0  2  0  0  0  2   0   0  1  2  1  1
4-3-1-2      2  0  0  1  0  3  0  0   0   0  1  2  1  1